### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by HoardsSwords** [DLCIncluded/MQ#2]
Hello! I noticed a few typos while checking out your questionnaire so I thought I would share them here in case it's helpful. 😄 

In questions.txt:
- Line 9
suggested edit: I find social interactions more comfortable if communicating about `a topic` of interest to me.

- Line 34
suggested edit: When there is a lot of information to consider, I often struggle to make `a decision`.

**Comment by DLCIncluded** [comment]
Hey thanks! 
Another user pointed that out yesterday I think, and I fixed it on the site, I just forgot to update the txt file lol the text file is just there as a reference, I had copied them all off the PDF from the source and there were a few issues from that
I'll get it updated tho thanks for the reminder!

**Comment by HoardsSwords** [comment]
Oh shoot sorry! I didn't think to check the closed issues section, my mistake. Thank you for the update!

**Comment by DLCIncluded** [comment]
Absolutely no issue! I forgot to update the text file, and I would have ran into issues (or someone else if they clone from it) if I wanted to go back and use that file instead of hard coding the values in the code lol I appreciate it! 

Thank you for reporting it, I got it updated 😄  have a good one!
