### ISSUE TITLE
Consider framing the "score" purely in terms of monotropism

### ISSUE THREAD

**Issue by soulware** [DLCIncluded/MQ#4]
There is various commentary on twitter stating the questionnaire is focused on _monotropism_ and not autism.
Including authors of the questionnaire -

* https://twitter.com/mxoolong/status/1682636123493875712
* https://twitter.com/scrappapertiger/status/1682690128504922113

Would it make sense to simply reframe the "results" text at the end to be around a monotropism "score" to avoid this being misconstrued? And maybe indicate some level of "overlap" with an possible autistic category.

Specifically the `Autistic Likely/Autism possible/Autism unlikely` categories - 

https://github.com/DLCIncluded/MQ/blob/6cb976a0770bfc1feadea7a6df475c2c3f4ab407/app/src/App.vue#L176C1-L196C9

**Comment by oolong** [comment]
Thanks for this, I've been trying to work out how to note issues like this!

Ideally I'd love to see scores expressed as something like 'This is more monotropic than 45% of autistic people, 60% of ADHD people, and 88% of people who are neither, based on data from the initial validation study on the MQ.'

My stats knowledge is rusty, but I think you'd be wanting to use something like a [cumulative distribution function for a normal curve](https://en.wikipedia.org/wiki/Normal_distribution#Cumulative_distribution_functions) for this. If I can figure out exactly how, I'll comment here or possibly even have a go at coding it myself.

Alternatively, responses in the form '(slightly/much) (more/less) monotropic than the average autistic person' could also work?

The existing responses sound far too much like this is an autism assessment, and it's really much too soon to use the MQ that way.

p.s. I'm study co-author Fergus Murray.

**Comment by DLCIncluded** [comment]
Thank you both I am working on fixes for this now, like I said in my disclaimers I'm no doctor lol I just gathered info from elsewhere and tried putting it together so apologies for some of that being wrong!

I feel like that stats is a bit over my head but I can definitely reword the scoring portion at least for now as to not give the wrong impression, I apologize for the misunderstanding!

**Comment by oolong** [comment]
Thanks David, really appreciate it! I've got a friend from the Monotropism Discord looking at the stats, so I'll see if we can do most of the work for you on that...

**Comment by DLCIncluded** [comment]
If so that would be great! I will gladly get it into the website if someone can do the math or give equations that I can worth with lol 

For now I have reworked that section to look like this: 

![image](https://github.com/DLCIncluded/MQ/assets/23517228/e5361af6-25ad-4966-9549-68b984c6ae80)

The build with that version will be up shortly, and I will be happy to make any further updates/changes to make this better

**Comment by Pi2048** [comment]
Hi David, I'm @oolong 's friend from Discord looking at the statistics.

Since there's some maths involved, I suggest using the math.js library to simplify the calculations. But my Javascript/npm is not nearly fluent enough to provide a direct pull request.

In the math.js sandbox, they include the library with `<script src="https://unpkg.com/mathjs/lib/browser/math.js"></script>`. After that, the following code allows you to generate a percentile score.

```
var x = 4.2 // the average score of the user
var mean = 4.15 // the mean of the distribution we're comparing to
var sd = 0.347 // the standard deviation of the distribution we're comparing to
    
print("The user's score puts them in the " + math.ceil(100*(1 - math.erf((mean - x ) / (math.sqrt(2) * sd))) / 2) + "th percentile of the autistic population.") // In the example, it should say '56th percentile'
```

**Comment by DLCIncluded** [comment]
Due to rounding, wasnt able to get 4.20 exactly as a test scenerio, but with the mathjs implemented its looking good: 
![image](https://github.com/DLCIncluded/MQ/assets/23517228/b054540e-b22c-4eaa-a10f-5180c6a94b84)
![image](https://github.com/DLCIncluded/MQ/assets/23517228/1889d77c-5e4d-47b8-a7e3-923de7552772)

but comparing these to the sandbox, they line up with the math if I mirror 4.19 and 4.21 they show as 55th and 57th respectively
@oolong please let me know what you think, and I can get that built and deployed, and again thank you all for taking the time to help with this, I really appreciate it

**Comment by Pi2048** [comment]
I expect that @oolong will want to clarify the score a bit further 😊. I looked it up online, and apparently there's some confusion about what 'being in a percentile' means. To clarify my code: if it says you're in the 56th percentile, that means that at least* 55% of the population has scores lower than yours.

My logic is that I view percentiles as boxes: you can be in the 1st, 2nd, 3rd, ..., 100th box. Other people think percentiles are numbered 0th, 1st, ..., 99th.

\* because of rounding, the exact number will usually be a bit higher, but below 56.

**Comment by DLCIncluded** [comment]
Yea stats were never my strong suit lol, but I did put a link to the percentile wikipedia for clarification on how that works, as not everyone knows percentiles like you said
We can always leave this out, but the math is here, and we can either leave it out or toss it in, but I'll leave that up to oolong

**Comment by oolong** [comment]
I'd suggest adding something like "This means you're more monotropic than about x% of autistic people" - I think that's easy to understand, and including 'about' acknowledges that it's a little bit fuzzy.

**Comment by DLCIncluded** [comment]
Deployed a build, so this is what it is currently displaying:
![image](https://github.com/DLCIncluded/MQ/assets/23517228/05ada576-30c6-46f5-9d03-09f7b890e772)

**Comment by DLCIncluded** [comment]
@oolong I did want to run this edit by you, I had previously had the slider to show visually where you fell in relation, and have modified it to look/work inline with the new/proper way of comparing the scores to the averages, what do you think of this:
![image](https://github.com/DLCIncluded/MQ/assets/23517228/0e509f5b-c144-4923-b124-064673b92fb4)

This is totally optional, I had just toyed around with the slider library and since I learned it for this project I'd like to include it if it doesn't cause confusion or misleading info. It just plots your average in relation to the averages of people with and with out Autism going off of the 4.15 and 3.19 respectively. If you feel this is not good to use, I will not deploy it as it was just for fun anyways 😄

**Comment by oolong** [comment]
I was wondering about having something like this but showing it against the graph from the paper with the two normal distributions. What do you think?

I think X and Y here are probably a little confusing as they stand.

Also - would you be up for adding a % to show how people compare with the non-autistic population, as well?

**Comment by DLCIncluded** [comment]
For the first point I can definitely try, which graph are we looking at specifically?

For the X/Y I had the same thought, the issue I had was on smaller screens it was difficult to not have them overlap if I put like "person with autism" I will definitely try to find a way to make that better. 

And for the last question, yes I actually already did the math I just forgot to add it to the UI lol I will do that too when I get back home

**Comment by acrostich** [comment]
Please avoid person-first terminology (i.e., people with autism), as per earlier in the text, 'Autistic person' or 'Autistic individual' or 'Autistic folk' is preferred. For non-Autistic person you can either use that or 'Allistic person'.

Identity-first terminology is the preferred one of most Autistic folks. 

(I prefer Autist as a noun, but that's not a common preference, however if you need to shorten the text to fit on small screens it is a valid option.)

Thank you for having created this online version of the MQ.

**Comment by DLCIncluded** [comment]
I updated the language, thank you for pointing it out @acrostich . I don't feel strongly about it either way, but you're absolutely right, it does seem to be more widely preferred.

With graph(not deployed):
![image](https://github.com/DLCIncluded/MQ/assets/23517228/c504d439-eda4-427f-88d5-b028ddf5917f)

Without graph(deployed and on site now):
![image](https://github.com/DLCIncluded/MQ/assets/23517228/2fc05110-f7bd-4133-9831-91b70d3e5a0a)

**Comment by oolong** [comment]
Oh sorry, it was in Valeria's poster presentation, not the paper itself. I meant this:
![Screenshot_2023-07-24-13-29-30-56_1843fd3f74f49144123f76a000cd5e7e](https://github.com/DLCIncluded/MQ/assets/144721/647f804e-4085-4c38-ba72-30c7955f5267)
(I'll double check with her if it would be okay to use here...)

**Comment by DLCIncluded** [comment]
Gotcha! I am not sure how I can implement that, but definitely can attempt

**Comment by DLCIncluded** [comment]
Also @oolong I sent you an email, I'm not sure if it was a valid email, was yourname at gmail, I believe I found it on your site (it also may have ended up in spam) about another question someone brought up: https://github.com/DLCIncluded/MQ/issues/7
I wasn't able to message you on twitter, and it wont let me tag you in that issue, if you could take a look I'd appreciate it. That question is about changing the scoring, and I believe it is not how it should be handled but I would love your input 😄 thank you!

**Comment by oolong** [comment]
Thanks. I'm ***@***.*** or ***@***.***, so I won't have got
that!

I'll pass the question along. I think they're right...

**Comment by oolong** [comment]
Val confirms it's fine to use the graph, and is nearly sure that her approach to N/A answers was what that commenter suggested (but will check tomorrow).

**Comment by oolong** [comment]
Small suggestions (hope it's okay to stick these here, seems easier than opening separate Issues or starting a merge request):
Can it say 'Your average' rather than just 'Average:'? A few people are getting confused by that!

**Comment by oolong** [comment]
And I wonder if it would be good to say something like 'monotropism, a trait associated with autism' in the disclaimer about it not being an autism assessment?

Thank you!

**Comment by oolong** [comment]
Hey, would you mind rephrasing the reporting of results to be just a little more cautious still? 'suggests' rather than 'means', and something about this being based on data from the initial validation study? 

And maybe just add, after 'Original credit' on the first page: 'This is a pre-print, meaning it is currently awaiting peer review.'

Thanks again David!

(and do say if you'd prefer me to use this Issue-tracking system in the way it's actually intended!)

**Comment by DLCIncluded** [comment]
Was on vacation last week so just getting to these now sorry for the delay!
I absolutely love the feedback and it is totally fine that they're all in this thread, working on these now

**Comment by oolong** [comment]
A possible edit of the graph to match up with a slider, if this is any help...
![image](https://github.com/DLCIncluded/MQ/assets/144721/589f0ab9-ab0e-44b0-a067-6f57e1569d1c)

**Comment by DLCIncluded** [comment]
Put in the suggested changes, also added a thank you at the top. 

I am still trying to determine if I can get the graph in there and have it be dynamic to show your avg score, if not I may just put the  image there, and put in a description saying something like "this is a image of a graph from the initial validation study, you can compare your average to the results of their findings"

thank you again for your help on this!

**Comment by DLCIncluded** [comment]
Going to close this out, as the initial issue is resolved, have spun off a new 'issue' marked as an enhancement for the graph changes so this thread doesn't get confusing, thanks again everyone
new issue for graph changes: https://github.com/DLCIncluded/MQ/issues/10
